import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
const routes = [
  "/",
  "/gastos",
  "/equipaje",
  "/compras",
  "/documentos",
  "/ruta",
  "/hoy",
  "/emergencia",
  "/diario",
  "/info",
  "/lugares",
  "/estadisticas",
  "/reportes",
  "/ajustes",
  "/mas",
];
async function walk(dir) {
  const result = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, e.name);
    if (e.isDirectory()) result.push(...(await walk(path)));
    else result.push(path);
  }
  return result;
}
const assets = (await walk(".next/static"))
  .filter((p) => /\.(js|css|woff2?|png|svg)$/.test(p))
  .map((p) => p.replace(".next/", "/_next/"));
const build = (await readFile(".next/BUILD_ID", "utf8")).trim();
const precache = [
  ...routes,
  ...assets,
  "/logo.svg",
  "/manifest.webmanifest",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/maskable-512.png",
];
const source = `/* Generated by scripts/build-sw.mjs. Do not edit. */
const CACHE=${JSON.stringify("trip-" + build)};
const PRECACHE=${JSON.stringify(precache)};
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(PRECACHE))));
self.addEventListener('activate',event=>event.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith('trip-')&&key!==CACHE)await caches.delete(key);await self.clients.claim();})()));
self.addEventListener('message',event=>{if(event.data==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('fetch',event=>{
 const req=event.request,url=new URL(req.url);
 if(req.method!=='GET'||url.origin!==self.location.origin||url.pathname.startsWith('/api/'))return;
 if(req.mode==='navigate'){
  event.respondWith((async()=>{const cache=await caches.open(CACHE);const stored=await cache.match(url.pathname);if(stored)return stored;try{return await fetch(req);}catch{return (await cache.match('/'));}})());return;
 }
 if(url.pathname.startsWith('/_next/static/')||PRECACHE.includes(url.pathname))event.respondWith((async()=>{const cache=await caches.open(CACHE);const stored=await cache.match(req);if(stored)return stored;const response=await fetch(req);if(response.ok)await cache.put(req,response.clone());return response;})());
});
`;
await writeFile("public/sw.js", source);
console.log(
  "Service worker generado:",
  routes.length,
  "rutas y",
  assets.length,
  "recursos.",
);
